# Konfigurasi untuk lingkungan development
development:
  type: 'mysql'
  host: 'semogajayastore.my.id'
  port: 3306
  username: 'semogaj2_LIS'
  password: 'HafizhBobby'
  database: 'semogaj2_tatLIS'
  entities: ['dist/**/*.entity{.ts,.js}']
  synchronize: true # Set ke false di production!